// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace LibRender {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ShaderSources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ShaderSources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("LibRender.ShaderSources", typeof(ShaderSources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static byte[] hdrpass_fs {
            get {
                object obj = ResourceManager.GetObject("hdrpass_fs", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] lightpass_fs {
            get {
                object obj = ResourceManager.GetObject("lightpass_fs", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] onscreenquad_vs {
            get {
                object obj = ResourceManager.GetObject("onscreenquad_vs", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] textcopy_fs {
            get {
                object obj = ResourceManager.GetObject("textcopy_fs", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] text_fs {
            get {
                object obj = ResourceManager.GetObject("text_fs", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] text_vs {
            get {
                object obj = ResourceManager.GetObject("text_vs", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] uielement_fs {
            get {
                object obj = ResourceManager.GetObject("uielement_fs", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] uielement_vs {
            get {
                object obj = ResourceManager.GetObject("uielement_vs", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] deferred_geometry_fs {
            get {
                object obj = ResourceManager.GetObject("deferred_geometry_fs", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] deferred_geometry_vs {
            get {
                object obj = ResourceManager.GetObject("deferred_geometry_vs", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] forward_geometry_fs {
            get {
                object obj = ResourceManager.GetObject("forward_geometry_fs", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] forward_geometry_vs {
            get {
                object obj = ResourceManager.GetObject("forward_geometry_vs", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] multisample_hdrpass_fs {
            get {
                object obj = ResourceManager.GetObject("multisample_hdrpass_fs", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] forward_geometry_unshaded_fs {
            get {
                object obj = ResourceManager.GetObject("forward_geometry_unshaded_fs", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
